package tk.mybatis.simple.model.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_authority
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleAuthority {
    /**
     * 角色权限关联id
     */
    private Integer id;

    /**
     * 权限id
     */
    private Integer authorityId;

    /**
     * 角色id
     */
    private Integer roleId;

    /**
     * 获取角色权限关联id
     *
     * @return id - 角色权限关联id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置角色权限关联id
     *
     * @param id 角色权限关联id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取权限id
     *
     * @return authority_id - 权限id
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * 设置权限id
     *
     * @param authorityId 权限id
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * 获取角色id
     *
     * @return role_id - 角色id
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * 设置角色id
     *
     * @param roleId 角色id
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}