package tk.mybatis.simple.mapper;

import java.util.List;
import tk.mybatis.simple.model.entity.RoleAuthority;

public interface RoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated
     */
    int insert(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated
     */
    RoleAuthority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated
     */
    List<RoleAuthority> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleAuthority record);
}